---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    app.quarkus.io/commit-id: a7f3f7553bd6685b5f43a37bad573e035a2fe962
    app.quarkus.io/build-timestamp: 2021-09-22 - 04:39:46 +0000
  labels:
    app.kubernetes.io/name: cos-fleetshard-sync
    app.kubernetes.io/version: latest
    app.kubernetes.io/part-of: cos
  name: cos-fleetshard-sync
imagePullSecrets:
  - name: cos-pull-secret
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    app.quarkus.io/commit-id: a7f3f7553bd6685b5f43a37bad573e035a2fe962
    app.quarkus.io/build-timestamp: 2021-09-22 - 04:39:46 +0000
    prometheus.io/scrape: "true"
    prometheus.io/path: /q/metrics
    prometheus.io/port: "8080"
    prometheus.io/scheme: http
  labels:
    app.kubernetes.io/name: cos-fleetshard-sync
    app.kubernetes.io/part-of: cos
    app.kubernetes.io/version: latest
  name: cos-fleetshard-sync
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
  selector:
    app.kubernetes.io/name: cos-fleetshard-sync
    app.kubernetes.io/part-of: cos
    app.kubernetes.io/version: latest
  type: ClusterIP
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  annotations:
    app.quarkus.io/commit-id: a7f3f7553bd6685b5f43a37bad573e035a2fe962
    app.quarkus.io/build-timestamp: 2021-09-22 - 04:39:46 +0000
  labels:
    app.kubernetes.io/name: cos-fleetshard-sync
    app.kubernetes.io/version: latest
    app.kubernetes.io/part-of: cos
  name: cos-fleetshard-sync
rules:
  - apiGroups:
      - cos.bf2.org
    resources:
      - managedconnectors
      - managedconnectors/status
      - managedconnectors/finalizers
      - managedconnectorclusters
      - managedconnectorclusters/status
      - managedconnectorclusters/finalizers
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - cos.bf2.org
    resources:
      - managedconnectoroperators
      - managedconnectoroperators/status
      - managedconnectoroperators/finalizers
    verbs:
      - get
      - list
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  annotations:
    app.quarkus.io/commit-id: a7f3f7553bd6685b5f43a37bad573e035a2fe962
    app.quarkus.io/build-timestamp: 2021-09-22 - 04:39:46 +0000
  labels:
    app.kubernetes.io/name: cos-fleetshard-sync
    app.kubernetes.io/version: latest
    app.kubernetes.io/part-of: cos
  name: cos-fleetshard-sync
roleRef:
  kind: Role
  apiGroup: rbac.authorization.k8s.io
  name: cos-fleetshard-sync
subjects:
  - kind: ServiceAccount
    name: cos-fleetshard-sync
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cos-fleetshard-sync-view
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: view
subjects:
  - kind: ServiceAccount
    name: cos-fleetshard-sync
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.quarkus.io/commit-id: a7f3f7553bd6685b5f43a37bad573e035a2fe962
    app.quarkus.io/build-timestamp: 2021-09-22 - 04:39:46 +0000
    prometheus.io/scrape: "true"
    prometheus.io/path: /q/metrics
    prometheus.io/port: "8080"
    prometheus.io/scheme: http
  labels:
    app.kubernetes.io/name: cos-fleetshard-sync
    app.kubernetes.io/version: latest
    app.kubernetes.io/part-of: cos
  name: cos-fleetshard-sync
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: cos-fleetshard-sync
      app.kubernetes.io/version: latest
      app.kubernetes.io/part-of: cos
  template:
    metadata:
      annotations:
        app.quarkus.io/commit-id: a7f3f7553bd6685b5f43a37bad573e035a2fe962
        app.quarkus.io/build-timestamp: 2021-09-22 - 04:39:46 +0000
        prometheus.io/scrape: "true"
        prometheus.io/path: /q/metrics
        prometheus.io/port: "8080"
        prometheus.io/scheme: http
      labels:
        app.kubernetes.io/name: cos-fleetshard-sync
        app.kubernetes.io/version: latest
        app.kubernetes.io/part-of: cos
    spec:
      containers:
        - env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: SMALLRYE_CONFIG_LOCATIONS
              value: "/mnt/app-config-map,/mnt/app-secret"
          image: quay.io/rhoas/cos-fleetshard-sync:latest
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /q/health/live
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 0
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 10
          name: cos-fleetshard-sync
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /q/health/ready
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 0
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 10
          volumeMounts:
            - mountPath: /mnt/app-secret
              name: app-secret
              readOnly: false
            - mountPath: /mnt/app-config-map
              name: app-config-map
              readOnly: false
      serviceAccount: cos-fleetshard-sync
      volumes:
        - name: app-secret
          secret:
            optional: false
            secretName: cos-fleetshard-sync-config
        - configMap:
            name: cos-fleetshard-sync-config
            optional: false
          name: app-config-map
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  annotations:
    app.quarkus.io/commit-id: a7f3f7553bd6685b5f43a37bad573e035a2fe962
    app.quarkus.io/build-timestamp: 2021-09-22 - 04:39:46 +0000
  labels:
    app.kubernetes.io/name: cos-fleetshard-sync
    app.kubernetes.io/version: latest
    app.kubernetes.io/part-of: cos
  name: cos-fleetshard-sync
spec:
  endpoints:
    - interval: 30s
      path: /q/metrics
      port: http
      scheme: http
  selector:
    matchLabels:
      app.kubernetes.io/name: cos-fleetshard-sync
      app.kubernetes.io/version: latest
      app.kubernetes.io/part-of: cos
