---
apiVersion: "v1"
kind: "ServiceAccount"
metadata:
  annotations: {}
  labels:
    app.kubernetes.io/name: "cos-fleetshard-sync"
    app.kubernetes.io/part-of: "cos"
    app.kubernetes.io/version: "latest"
  name: "cos-fleetshard-sync"
imagePullSecrets:
- name: "cos-pull-secret"
---
apiVersion: "v1"
kind: "Service"
metadata:
  annotations:
    prometheus.io/path: "/q/metrics"
    prometheus.io/port: "8080"
    prometheus.io/scheme: "http"
    prometheus.io/scrape: "true"
  labels:
    app.kubernetes.io/name: "cos-fleetshard-sync"
    app.kubernetes.io/part-of: "cos"
    app.kubernetes.io/version: "latest"
  name: "cos-fleetshard-sync"
spec:
  ports:
  - name: "http"
    port: 80
    targetPort: 8080
  selector:
    app.kubernetes.io/name: "cos-fleetshard-sync"
    app.kubernetes.io/part-of: "cos"
    app.kubernetes.io/version: "latest"
  type: "ClusterIP"
---
apiVersion: "rbac.authorization.k8s.io/v1"
kind: "Role"
metadata:
  annotations: {}
  labels:
    app.kubernetes.io/name: "cos-fleetshard-sync"
    app.kubernetes.io/part-of: "cos"
    app.kubernetes.io/version: "latest"
  name: "cos-fleetshard-sync"
rules:
- apiGroups:
  - "cos.bf2.org"
  resources:
  - "managedconnectors"
  - "managedconnectors/status"
  - "managedconnectors/finalizers"
  - "managedconnectorclusters"
  - "managedconnectorclusters/status"
  - "managedconnectorclusters/finalizers"
  verbs:
  - "create"
  - "delete"
  - "get"
  - "list"
  - "patch"
  - "update"
  - "watch"
- apiGroups:
  - "cos.bf2.org"
  resources:
  - "managedconnectoroperators"
  - "managedconnectoroperators/status"
  - "managedconnectoroperators/finalizers"
  verbs:
  - "get"
  - "list"
  - "watch"
- apiGroups:
  - ""
  resources:
  - "secrets"
  verbs:
  - "create"
  - "delete"
  - "get"
  - "list"
  - "patch"
  - "update"
  - "watch"
---
apiVersion: "rbac.authorization.k8s.io/v1"
kind: "RoleBinding"
metadata:
  annotations: {}
  labels:
    app.kubernetes.io/name: "cos-fleetshard-sync"
    app.kubernetes.io/part-of: "cos"
    app.kubernetes.io/version: "latest"
  name: "cos-fleetshard-sync"
roleRef:
  apiGroup: "rbac.authorization.k8s.io"
  kind: "Role"
  name: "cos-fleetshard-sync"
subjects:
- kind: "ServiceAccount"
  name: "cos-fleetshard-sync"
---
apiVersion: "rbac.authorization.k8s.io/v1"
kind: "RoleBinding"
metadata:
  name: "cos-fleetshard-sync-view"
roleRef:
  apiGroup: "rbac.authorization.k8s.io"
  kind: "ClusterRole"
  name: "view"
subjects:
- kind: "ServiceAccount"
  name: "cos-fleetshard-sync"
---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  annotations:
    prometheus.io/path: "/q/metrics"
    prometheus.io/port: "8080"
    prometheus.io/scheme: "http"
    prometheus.io/scrape: "true"
  labels:
    app.kubernetes.io/name: "cos-fleetshard-sync"
    app.kubernetes.io/part-of: "cos"
    app.kubernetes.io/version: "latest"
  name: "cos-fleetshard-sync"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: "cos-fleetshard-sync"
      app.kubernetes.io/part-of: "cos"
      app.kubernetes.io/version: "latest"
  template:
    metadata:
      annotations:
        prometheus.io/path: "/q/metrics"
        prometheus.io/port: "8080"
        prometheus.io/scheme: "http"
        prometheus.io/scrape: "true"
      labels:
        app.kubernetes.io/name: "cos-fleetshard-sync"
        app.kubernetes.io/part-of: "cos"
        app.kubernetes.io/version: "latest"
    spec:
      containers:
      - env:
        - name: "KUBERNETES_NAMESPACE"
          valueFrom:
            fieldRef:
              fieldPath: "metadata.namespace"
        - name: "SMALLRYE_CONFIG_SOURCE_FILE_LOCATIONS"
          value: "/mnt/app-secret"
        - name: "SMALLRYE_CONFIG_LOCATIONS"
          value: "/mnt/app-config"
        image: "quay.io/rhoas/cos-fleetshard-sync:latest"
        imagePullPolicy: "Always"
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: "/q/health/live"
            port: 8080
            scheme: "HTTP"
          initialDelaySeconds: 0
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 10
        name: "cos-fleetshard-sync"
        ports:
        - containerPort: 8080
          name: "http"
          protocol: "TCP"
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: "/q/health/ready"
            port: 8080
            scheme: "HTTP"
          initialDelaySeconds: 0
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 10
        resources:
          limits:
            cpu: "1500m"
            memory: "512Mi"
          requests:
            cpu: "500m"
            memory: "256Mi"
        volumeMounts:
        - mountPath: "/mnt/app-config"
          name: "app-config"
          readOnly: false
        - mountPath: "/mnt/app-secret"
          name: "app-secret"
          readOnly: false
      serviceAccount: "cos-fleetshard-sync"
      volumes:
      - name: "app-secret"
        secret:
          defaultMode: 384
          optional: false
          secretName: "cos-fleetshard-sync-config"
      - configMap:
          defaultMode: 384
          name: "cos-fleetshard-sync-config"
          optional: false
        name: "app-config"
---
apiVersion: "monitoring.coreos.com/v1"
kind: "ServiceMonitor"
metadata:
  annotations: {}
  labels:
    app.kubernetes.io/name: "cos-fleetshard-sync"
    app.kubernetes.io/part-of: "cos"
    app.kubernetes.io/version: "latest"
  name: "cos-fleetshard-sync"
spec:
  endpoints:
  - interval: "30s"
    path: "/q/metrics"
    port: "http"
    scheme: "http"
  selector:
    matchLabels:
      app.kubernetes.io/name: "cos-fleetshard-sync"
      app.kubernetes.io/part-of: "cos"
      app.kubernetes.io/version: "latest"