#kubectl create clusterrolebinding strimzi-cluster-operator-namespaced 
#  --clusterrole=strimzi-cluster-operator-namespaced 
#  --serviceaccount my-namespace:strimzi-cluster-operator
# @see https://github.com/strimzi/strimzi-kafka-operator/blob/0.32.0/install/cluster-operator/021-ClusterRoleBinding-strimzi-cluster-operator.yaml

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: strimzi-cluster-operator
  labels:
    app: strimzi
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: strimzi-cluster-operator-global
subjects:
- kind: ServiceAccount
  name: strimzi-cluster-operator
  namespace: myproject
