#kubectl create clusterrolebinding strimzi-cluster-operator-entity-operator-delegation 
#  --clusterrole=strimzi-entity-operator 
#  --serviceaccount my-namespace:strimzi-cluster-operator
# @see https://github.com/strimzi/strimzi-kafka-operator/blob/0.32.0/install/cluster-operator/031-RoleBinding-strimzi-cluster-operator-entity-operator-delegation.yaml

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: strimzi-cluster-operator-entity-operator-delegation
  labels:
    app: strimzi
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: strimzi-entity-operator
subjects:
- kind: ServiceAccount
  name: strimzi-cluster-operator
  namespace: myproject
