#kubectl create clusterrolebinding strimzi-cluster-operator-topic-operator-delegation 
#  --clusterrole=strimzi-topic-operator 
#  --serviceaccount my-namespace:strimzi-cluster-operator

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app: strimzi
  name: strimzi-cluster-operator-topic-operator-delegation
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: strimzi-topic-operator 
subjects:
- kind: ServiceAccount
  name: strimzi-cluster-operator
  namespace: myproject