resources:
  - ../base

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: cos-fleetshard-operator-camel-config
    files:
      - application.properties=app-config/application.properties

patchesJson6902:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: cos-fleetshard-operator-camel
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: COS_OPERATOR_ID
          value: cos-fleetshard-operator-camel
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: COS_OPERATOR_VERSION
          value: "1.5.0"
  - target:
      group: rbac.authorization.k8s.io
      version: v1
      kind: ClusterRoleBinding
      name: cos-fleetshard-operator-camel
    patch: |-
      - op: replace
        path: /subjects/0/namespace
        value: "cos"