= cos-fleetshard-operator-debezium


== configuration

* create application config
+
[source,shell]
----
kubectl create configmap cos-fleetshard-operator-debezium-config \
    --from-file=../etc/kubernetes/operator-debezium/base/app-config/application.properties
----
+
[IMPORTANT]
====
the provided `application.properties` is only a template, copy it somewhere and adapt the command above
====

== local profile

Start Quarkus in dev mode and read the application configuration from the current namespace.

[source,shell]
----
export KUBERNETES_NAMESPACE=$(oc project -q)
export COS_OPERATOR_ID=${some_value}
export COS_OPERATOR_VERSION==${some_value}

./mvnw -Dlocal
----

[IMPORTANT]
====
The `COS_OPERATOR_ID` should be synchronized with the value assigned by the addon bundle.
As of this commit, this would be `cos-fleetshard-operator-debezium-1.0.1`.

Please check the bundles repository for this operator's latest cluster service version configuration and make sure this is set to the same value as the container's `COS_OPERATOR_ID` environment variable.

Additionally, the `COS_OPERATOR_VERSION` should be synchronized from the same location but should match the cluster service version configuration's environment variable of the same name.
As of this commit, this would be `1.5.0`.
====

By default, the application searches for:

* **ConfigMap**: cos-fleetshard-operator-debezium-config

To change the default values, use the following system properties:
- quarkus.kubernetes-config.namespace
- quarkus.kubernetes-config.config-maps

== configuration options

[cols="1,1,1"]
|===
| Property | Default | Description

| cos.operator.id
|
| the id of the operator

| cos.operator.version
|
| the version of the operator

| cos.operators.namespace
| ${kubernetes.namespace}
| the namespace where operator related resources are created
|===
