api:
  - cos-fleetshard-api/**/*
common:
  - cos-fleetshard-support/**/*
operator:
  - cos-fleetshard-operator/**/*
  - cos-fleetshard-operator-it/**/*
camel:
  - cos-fleetshard-operator-camel/**/*
  - cos-fleetshard-operator-camel-it/**/*
debezium:
  - cos-fleetshard-operator-debezium/**/*
  - cos-fleetshard-operator-debezium-it/**/*
sync:
  - cos-fleetshard-sync/**/*
  - cos-fleetshard-sync-it/**/*
test:
  - cos-fleetshard-it/**/*
  - cos-fleetshard-sync-it/**/*
  - cos-fleetshard-operator-camel-it/**/*
  - cos-fleetshard-operator-debezium-it/**/*
tools:
  - cos-build-tools/**/*
github_ci:
  - .github/**/*

