resources:
- ../../../base/apps/cos-fleetshard-sync

generatorOptions:
    disableNameSuffixHash: true

configMapGenerator:
    - files:
          - application.properties=app-config/application.properties
      name: cos-fleetshard-sync-config
      behavior: replace

patchesJson6902:
- target:
    group: apps
    kind: Deployment
    name: cos-fleetshard-sync
    version: v1
  patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/imagePullPolicy
      value: "Always"

