/**
 * Connector Service Fleet Manager Private APIs
 * Connector Service Fleet Manager apis that are used by internal services.
 *
 * The version of the OpenAPI document: 0.0.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.bf2.cos.fleet.manager.client;

import javax.ws.rs.GET;
import javax.ws.rs.Path;
import javax.ws.rs.ProcessingException;
import javax.ws.rs.Produces;
import javax.ws.rs.core.MediaType;

import org.bf2.cos.fleet.manager.api.ApiException;

import com.fasterxml.jackson.databind.JsonNode;

public interface AuthApi {
    @GET
    @Path("/sso_providers")
    @Produces(MediaType.APPLICATION_JSON)
    JsonNode getSsoProviders()
        throws ApiException, ProcessingException;
}
