= cos-fleetshard

== requirements

* https://stedolan.github.io/jq/[jq]
* curl
* https://github.com/stern/stern[stern]
* https://github.com/openshift-online/ocm-cli[ocm]
* https://kubernetes.io/docs/tasks/tools/[kubectl]
* uuidgen
* https://github.com/bf2fc6cc711aee1a0c2a/cos-tools[cos-tools]
* https://minikube.sigs.k8s.io[minikube]

define the following env vars:

* COS_BASE_PATH -> base URL for the managed connector service control plane
* KAS_BASE_PATH -> base URL for the managed kafka service control plane


[TIP]
====
I use https://direnv.net[direnv] with the following set-up

[source,shell]
----
export OCM_CONFIG=$PWD/.ocm.json
export KUBECONFIG=$PWD/.kube/config
export COS_BASE_PATH=https://cos-fleet-manager-cos.rh-fuse-153f1de160110098c1928a6c05e19444-0000.eu-de.containers.appdomain.cloud
export KAS_BASE_PATH=https://api.openshift.com
----
====

== local installation

[NOTE]
====
This is an example installation that consists in:

- 1 sync
- 1 camel connector operator
- 1 debezium connector operator
====

* *set-up minikube*
+
[source,shell]
----
# you may need to tune this command
minikube start --profile cos --cpus=4 --memory=4096
----

* *install camel-k 1.6.x*
+
[source,shell]
----
kamel install --olm=false --skip-registry-setup
----

* *install strimzi 0.25.0*
+
[source,shell]
----
kubectl apply -f 'https://strimzi.io/install/latest?namespace=default'
----


* *install images*
+
[source,shell]
----
eval $(minikube --profile cos docker-env)
mvn clean install -DskipTests=true -Pcontainer-build
----

* *install CRDs*
+
[source,shell]
----
kubectl apply -f etc/kubernetes/managedconnectorclusters.cos.bf2.org-v1.yml
kubectl apply -f etc/kubernetes/managedconnectoroperators.cos.bf2.org-v1.yml
kubectl apply -f etc/kubernetes/managedconnectors.cos.bf2.org-v1.yml
----

* *install operators and sync*
+
[source,shell]
----
kubectl apply -k etc/kubernetes/operator-camel/local
kubectl apply -k etc/kubernetes/operator-debezium/local
kubectl apply -k etc/kubernetes/sync/local
----
+
At this point, operators and sync are deployed, but they are not running as replica is set to 0 by default because some resources have to be configured.
+
[source,shell]
----
➜ kubectl get deployments
NAME                               READY   UP-TO-DATE   AVAILABLE   AGE
camel-k-operator                   1/1     1            1           2d3h
cos-fleetshard-operator-camel      0/0     0            0           6s
cos-fleetshard-operator-debezium   0/0     0            0           5s
cos-fleetshard-sync                0/0     0            0           4s
strimzi-cluster-operator           1/1     1            1           2d3h
----
+
* *configure secrets*
+
[NOTE]
====
This creates a new cluster on the fleet manager, remember to delete it once done
====
+
[source,shell]
----
SUFFIX=$(uuidgen | tr -d '-')
create-cluster-secret $(create-cluster "$USER-$SUFFIX" | jq -r '.id') cos-fleetshard-sync-config
----
+
* *scale deployments*
+
[source,shell]
----
kubectl scale deployment -l "app.kubernetes.io/part-of=cos" --replicas=1
----

== testing

* *set-up minikube*
+
[source,shell]
----
# you may need to tune this command
minikube start --profile cos-testing
----

* *install CRDs*
+
[source,shell]
----
# install custom resources
kubectl apply -f etc/kubernetes/managedconnectorclusters.cos.bf2.org-v1.yml
kubectl apply -f etc/kubernetes/managedconnectoroperators.cos.bf2.org-v1.yml
kubectl apply -f etc/kubernetes/managedconnectors.cos.bf2.org-v1.yml
kubectl apply -f https://raw.githubusercontent.com/apache/camel-k/release-1.6.x/config/crd/bases/camel.apache.org_kameletbindings.yaml
kubectl apply -f https://raw.githubusercontent.com/strimzi/strimzi-kafka-operator/0.25.0/install/cluster-operator/041-Crd-kafkaconnect.yaml
kubectl apply -f https://raw.githubusercontent.com/strimzi/strimzi-kafka-operator/0.25.0/install/cluster-operator/047-Crd-kafkaconnector.yaml
----

* *run tests*
+
[source,shell]
----
mvn clean install
----

== components

- link:cos-fleetshard-sync/README.adoc[sync]
- link:cos-fleetshard-operator-camel/README.adoc[camel]
- link:cos-fleetshard-operator-debezium/README.adoc[debezium]
