= cos-fleetshard

== set-up

* requirements:
** https://stedolan.github.io/jq/[jq]
** curl
** https://github.com/stern/stern[stern]
** https://github.com/openshift-online/ocm-cli[ocm]
** https://kubernetes.io/docs/tasks/tools/[kubectl]
** uuidgen
** https://github.com/bf2fc6cc711aee1a0c2a/cos-tools[cos-tools]
** https://minikube.sigs.k8s.io[minikube]

* define the following env vars:
+
** COS_BASE_PATH -> base URL for the managed connector service control plane
** KAS_BASE_PATH -> base URL for the managed kafka service control plane
+
[TIP]
====
I use https://direnv.net[direnv] with the following set-up

[source,shell]
----
export OCM_CONFIG=$PWD/.ocm.json
export KUBECONFIG=$PWD/.kube/config
export COS_BASE_PATH=https://cos-fleet-manager-cos.rh-fuse-153f1de160110098c1928a6c05e19444-0000.eu-de.containers.appdomain.cloud
export KAS_BASE_PATH=https://api.openshift.com
----
====

* retrieve your ocm-offline-token from https://qaprodauth.cloud.redhat.com/openshift/token using the *__kafka_supporting_* account
+
** follow the steps on that page to download and install the ocm command-line tool, then run the ocm login with the provided token

== local installation

[NOTE]
====
This is an example installation that consists in:

- 1 sync
- 1 camel connector operator
- 1 debezium connector operator
====

* *set-up minikube*
+
[source,shell]
----
# you may need to tune cpus and memory depending on your laptop config
minikube start --profile cos --cpus=4 --memory=4096
----

* *install camel-k 1.8.x*
+
This will install Camel K in the running cluster, needed to create connectors based on it, so make sure the `minikube start` was successful.
+
[source,shell]
----
kamel install --olm=false --skip-registry-setup
----

* *install latest strimzi*
+
This will install strimzi in the running cluster, needed to create connectors based on Debezium, so make sure the `minikube start` was successful.
+
[source,shell]
----
kubectl apply -f 'https://strimzi.io/install/latest?namespace=default'
----


* *install images*
+
This step is only necessary if you want to run everything inside the cluster. For developing purposes, if you want to run the synchronizer and operators with `quarkus:dev`, that's not needed.
+
[source,shell]
----
eval $(minikube --profile cos docker-env)
./mvnw clean install -DskipTests=true -Pcontainer-build
----

* *configure pull secret*
+
In order to use private image on quay a pull secret need to be crated:
+
** copy the content of https://vault.devshift.net/ui/vault/secrets/managed-services/show/quay-org-accounts/rhoas/robots/rhoas-pull-docker[rhoas-pull-docker] to a local file
** create a pull secret:
+
[source,shell]
----
kubectl create secret generic addon-pullsecret \
    --from-file=.dockerconfigjson=${path of rhoas-pull-docker} \
    --type=kubernetes.io/dockerconfigjson
----

* *install CRDs*
+
This will install the CRDs for Managed Connectors, it's Operators and Clusters.
+
[source,shell]
----
./etc/scripts/deploy_fleetshard_crds.sh
----

* *install operators and sync*
+
[source,shell]
----
kubectl apply -k etc/kubernetes/operator-camel/local
kubectl apply -k etc/kubernetes/operator-debezium/local
kubectl apply -k etc/kubernetes/sync/local
----
+
At this point, operators and sync are deployed, but they are not running as replica is set to 0 by default because some resources have to be configured.
+
[source,shell]
----
➜ kubectl get deployments
NAME                               READY   UP-TO-DATE   AVAILABLE   AGE
camel-k-operator                   1/1     1            1           2d3h
cos-fleetshard-operator-camel      0/0     0            0           6s
cos-fleetshard-operator-debezium   0/0     0            0           5s
cos-fleetshard-sync                0/0     0            0           4s
strimzi-cluster-operator           1/1     1            1           2d3h
----
+
* *create cluster and configure secrets*
+
This section expects you to have https://github.com/bf2fc6cc711aee1a0c2a/cos-tools/tree/main/bin[cos-tools/bin] in your PATH, but you may also just run the scripts from inside the bin directory.
+
[NOTE]
====
This creates a new cluster for you on the fleet manager, remember to delete it once done.
====
+
[source,shell]
----
SUFFIX=$(uuidgen | tr -d '-')
create-cluster-secret $(create-cluster "$USER-$SUFFIX" | jq -r '.id') cos-fleetshard-sync-config
----
+
When you're done you may query for created clusters with `get-clusters` and delete it with `delete-clusters <cluster id>`.

* *scale deployments*
+
[source,shell]
----
kubectl scale deployment -l "app.kubernetes.io/part-of=cos" --replicas=1
----

== testing

[NOTE]
====
Although this section expects you to use a completely new kubernetes cluster, you may also just stop `camel-k-operator` and `strimzi-cluster-operator` and run the tests if you are an experienced user.
====

* *set-up minikube*
+
[source,shell]
----
# you may need to tune this command
minikube start --profile cos-testing
----

* *install CRDs*
+
[source,shell]
----
# install custom resources
./etc/scripts/deploy_fleetshard_crds.sh
./etc/scripts/deploy_camel-k_crds.sh
./etc/scripts/deploy_strimzi_crds.sh
----

* *run tests*
+
[source,shell]
----
./mvnw clean install
----

== components

- link:cos-fleetshard-sync/README.adoc[sync]
- link:cos-fleetshard-operator-camel/README.adoc[camel]
- link:cos-fleetshard-operator-debezium/README.adoc[debezium]
