apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rhoc
spec:
  ignoreDifferences:
    - kind: ServiceAccount
      jsonPointers:
        - /imagePullSecrets
        - /secrets
  destination:
    namespace: redhat-openshift-connectors
    server: https://kubernetes.default.svc
  project: default
  source:
    path: kustomize/overlays/dev/
    repoURL: https://github.com/bf2fc6cc711aee1a0c2a/cos-manifests
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - PruneLast=true
      - CreateNamespace=false
