---
apiVersion: "monitoring.coreos.com/v1"
kind: "ServiceMonitor"
metadata:
  labels:
    app.kubernetes.io/name: "cos-fleetshard-sync"
    app.kubernetes.io/part-of: "cos"
    app.kubernetes.io/version: "latest"
  name: "cos-fleetshard-sync"
spec:
  endpoints:
    - interval: "30s"
      path: "/q/metrics"
      port: "http"
      scheme: "http"
  selector:
    matchLabels:
      app.kubernetes.io/name: "cos-fleetshard-sync"
      app.kubernetes.io/part-of: "cos"
---
apiVersion: "monitoring.coreos.com/v1"
kind: "ServiceMonitor"
metadata:
  labels:
    app.kubernetes.io/name: "cos-fleetshard-operator-camel"
    app.kubernetes.io/part-of: "cos"
  name: "cos-fleetshard-operator-camel"
spec:
  endpoints:
    - interval: "30s"
      path: "/q/metrics"
      port: "http"
      scheme: "http"
  selector:
    matchLabels:
      app.kubernetes.io/name: "cos-fleetshard-operator-camel"
      app.kubernetes.io/part-of: "cos"
---
apiVersion: "monitoring.coreos.com/v1"
kind: "ServiceMonitor"
metadata:
  labels:
    app.kubernetes.io/name: "cos-fleetshard-operator-debezium"
    app.kubernetes.io/part-of: "cos"
  name: "cos-fleetshard-operator-debezium"
spec:
  endpoints:
    - interval: "30s"
      path: "/q/metrics"
      port: "http"
      scheme: "http"
  selector:
    matchLabels:
      app.kubernetes.io/name: "cos-fleetshard-operator-debezium"
      app.kubernetes.io/part-of: "cos"

