resources:
  - ../../base

nameSuffix: "-2"

commonLabels:
  app.kubernetes.io/name: "2"

patchesJson6902:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: cos-fleetshard-sync
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 0
      - op: replace
        path: /spec/template/spec/serviceAccount
        value: "cos-fleetshard-sync-2"
      - op: replace
        path: /spec/template/spec/containers/0/name
        value: "application"

