resources:
- ../../../base/apps/cos-fleetshard-sync

generatorOptions:
    disableNameSuffixHash: true

configMapGenerator:
  - files:
      - application.properties=app-config/application.properties
    name: cos-fleetshard-sync-config
    behavior: replace

patchesStrategicMerge: 
  - |- 
    $patch: delete
    apiVersion: rbac.authorization.k8s.io/v1
    kind: RoleBinding
    metadata:
      name: cos-fleetshard-sync-view

patchesJson6902:
- target:
    group: apps
    kind: Deployment
    name: cos-fleetshard-sync
    version: v1
  patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/imagePullPolicy
      value: "IfNotPresent"
