---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    app.quarkus.io/commit-id: 838fe144f235355f4b25e1f78744d65bf3b91705
    app.quarkus.io/build-timestamp: 2021-09-01 - 10:48:04 +0000
  labels:
    app.kubernetes.io/part-of: cos
    app.kubernetes.io/name: cos-fleetshard-operator-camel
    app.kubernetes.io/version: latest
  name: cos-fleetshard-operator-camel
imagePullSecrets:
  - name: cos-pull-secret
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    app.quarkus.io/commit-id: 838fe144f235355f4b25e1f78744d65bf3b91705
    app.quarkus.io/build-timestamp: 2021-09-01 - 10:48:04 +0000
    prometheus.io/scrape: "true"
    prometheus.io/path: /q/metrics
    prometheus.io/port: "8080"
    prometheus.io/scheme: http
  labels:
    app.kubernetes.io/name: cos-fleetshard-operator-camel
    app.kubernetes.io/part-of: cos
    app.kubernetes.io/version: latest
  name: cos-fleetshard-operator-camel
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
  selector:
    app.kubernetes.io/name: cos-fleetshard-operator-camel
    app.kubernetes.io/part-of: cos
    app.kubernetes.io/version: latest
  type: ClusterIP
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  annotations:
    app.quarkus.io/commit-id: 838fe144f235355f4b25e1f78744d65bf3b91705
    app.quarkus.io/build-timestamp: 2021-09-01 - 10:48:04 +0000
  labels:
    app.kubernetes.io/part-of: cos
    app.kubernetes.io/name: cos-fleetshard-operator-camel
    app.kubernetes.io/version: latest
  name: cos-fleetshard-operator-camel
rules:
  - apiGroups:
      - cos.bf2.org
    resources:
      - managedconnectors
      - managedconnectors/status
      - managedconnectors/finalizers
      - managedconnectoroperators
      - managedconnectoroperators/status
      - managedconnectoroperators/finalizers
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - camel.apache.org
    resources:
      - kameletbindings
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  annotations:
    app.quarkus.io/commit-id: 838fe144f235355f4b25e1f78744d65bf3b91705
    app.quarkus.io/build-timestamp: 2021-09-01 - 10:48:04 +0000
  labels:
    app.kubernetes.io/part-of: cos
    app.kubernetes.io/name: cos-fleetshard-operator-camel
    app.kubernetes.io/version: latest
  name: cos-fleetshard-operator-camel
roleRef:
  kind: Role
  apiGroup: rbac.authorization.k8s.io
  name: cos-fleetshard-operator-camel
subjects:
  - kind: ServiceAccount
    name: cos-fleetshard-operator-camel
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cos-fleetshard-operator-camel-view
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: view
subjects:
  - kind: ServiceAccount
    name: cos-fleetshard-operator-camel
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.quarkus.io/commit-id: 838fe144f235355f4b25e1f78744d65bf3b91705
    app.quarkus.io/build-timestamp: 2021-09-01 - 10:48:04 +0000
    prometheus.io/scrape: "true"
    prometheus.io/path: /q/metrics
    prometheus.io/port: "8080"
    prometheus.io/scheme: http
  labels:
    app.kubernetes.io/part-of: cos
    app.kubernetes.io/name: cos-fleetshard-operator-camel
    app.kubernetes.io/version: latest
  name: cos-fleetshard-operator-camel
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/part-of: cos
      app.kubernetes.io/name: cos-fleetshard-operator-camel
      app.kubernetes.io/version: latest
  template:
    metadata:
      annotations:
        app.quarkus.io/commit-id: 838fe144f235355f4b25e1f78744d65bf3b91705
        app.quarkus.io/build-timestamp: 2021-09-01 - 10:48:04 +0000
        prometheus.io/scrape: "true"
        prometheus.io/path: /q/metrics
        prometheus.io/port: "8080"
        prometheus.io/scheme: http
      labels:
        app.kubernetes.io/part-of: cos
        app.kubernetes.io/name: cos-fleetshard-operator-camel
        app.kubernetes.io/version: latest
    spec:
      containers:
        - env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: SMALLRYE_CONFIG_LOCATIONS
              value: "/mnt/app-config-map,/mnt/app-secret"
          image: quay.io/rhoas/cos-fleetshard-operator-camel:latest
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /q/health/live
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 0
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 10
          name: cos-fleetshard-operator-camel
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /q/health/ready
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 0
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 10
          volumeMounts:
            - mountPath: /mnt/app-secret
              name: app-secret
              readOnly: false
            - mountPath: /mnt/app-config-map
              name: app-config-map
              readOnly: false
      serviceAccount: cos-fleetshard-operator-camel
      volumes:
        - name: app-secret
          secret:
            optional: false
            secretName: cos-fleetshard-operator-camel-config
        - configMap:
            name: cos-fleetshard-operator-camel-config
            optional: false
          name: app-config-map
