resources:
  - kubernetes.yml

configMapGenerator:
  - name: cos-fleetshard-operator-camel-config
    files:
      - application.properties=app-config/application.properties
secretGenerator:
  - name: cos-fleetshard-operator-camel-config
    files:
      - application.properties=app-secret/application.properties

#images:
#  - name: quay.io/rhoas/cos-fleetshard-operator-camel:latest
#    newName: quay.io/lburgazzoli/cfs-c
#    newTag: latest

patchesJson6902:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: cos-fleetshard-operator-camel
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/name
        value: application
      - op: replace
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: "Never"
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: COS_OPERATOR_ID
          value: cos-fleetshard-operator-camel
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: COS_OPERATOR_VERSION
          value: "1.5.0"