---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cos-fleetshard-operator-camel
imagePullSecrets:
  - name: addon-pullsecret
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cos-fleetshard-operator-camel
rules:
# operator custom resources
- apiGroups:
  - cos.bf2.org
  resources:
  - managedconnectors
  - managedconnectors/status
  - managedconnectors/finalizers
  - managedconnectoroperators
  - managedconnectoroperators/status
  - managedconnectoroperators/finalizers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
# managed connector resources
- apiGroups:
  - ""
  resources:
  - secrets
  - configmaps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - camel.apache.org
  resources:
  - kameletbindings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cos-fleetshard-operator-camel-events
rules:
- apiGroups:
  - ""
  resources:
    - events
  verbs:
    - create
    - patch
    - get
    - list
    - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cos-fleetshard-operator-camel
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: cos-fleetshard-operator-camel
subjects:
- kind: ServiceAccount
  name: cos-fleetshard-operator-camel
  namespace: placeholder
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cos-fleetshard-operator-camel-events
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: cos-fleetshard-operator-camel-events
subjects:
  - kind: ServiceAccount
    name: cos-fleetshard-operator-camel
    namespace: placeholder
