resources:
  - kubernetes.yaml

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
  - name: mctr-9bsv0s1ol6qg02u5uqbg-deploy
    files:
      - connector=secrets/connector.json
      - kafka=secrets/kafka.json
      - meta=secrets/meta.json

commonLabels:
  cos.bf2.org/deployment.resource.version: "1"
  cos.bf2.org/connector.resource.version: "1"
  cos.bf2.org/cluster.id: 9bsv0s12q4r002h4440g
  cos.bf2.org/connector.id: 9bsv0s0e630g02od9u2g
  cos.bf2.org/deployment.id: 9bsv0s1ol6qg02u5uqbg
  cos.bf2.org/uow: 9bsv0s11r32002tqti40
  cos.bf2.org/operator.type: camel-connector-operator

patchesJson6902:
  - target:
      group: cos.bf2.org
      version: v1alpha1
      kind: ManagedConnector
      name: mctr-camel
    patch: |-
      - op: replace
        path: /spec/clusterId
        value: "9bsv0s12q4r002h4440g"
      - op: replace
        path: /spec/connectorId
        value: "9bsv0s0e630g02od9u2g"
      - op: replace
        path: /spec/deploymentId
        value: "9bsv0s1ol6qg02u5uqbg"
      - op: replace
        path: /spec/deployment/unitOfWork
        value: "9bsv0s11r32002tqti40"
      - op: replace
        path: /spec/deployment/connectorResourceVersion
        value: 1
      - op: replace
        path: /spec/deployment/deploymentResourceVersion
        value: 1