resources:
  - kubernetes.yml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: cos-fleetshard-operator-debezium-config
    files:
      - application.properties=app-config/application.properties
secretGenerator:
  - name: cos-fleetshard-operator-debezium-config
    files:
      - application.properties=app-secret/application.properties

patchesJson6902:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: cos-fleetshard-operator-debezium
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/name
        value: application
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: COS_OPERATOR_ID
          value: cos-fleetshard-operator-debezium
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: COS_OPERATOR_VERSION
          value: "1.5.0"