
resources:
  - namespace.yaml
  - camel-k
  - cos-fleetshard-sync
  - cos-fleetshard-operator-camel
  - cos-fleetshard-operator-debezium

namespace: redhat-openshift-connectors

patches:
  - target:
      group: rbac.authorization.k8s.io
      version: v1
      kind: ClusterRoleBinding
      name: ".*"
    patch: |-
      - op: replace
        path: /subjects/0/namespace
        value: "redhat-openshift-connectors"
