= cos-fleetshard-sync


== configuration

* create application config
+
[source,shell]
----
kubectl create configmap cos-fleetshard-sync-config \
    --from-file=../etc/kubernetes/sync/base/app-config/application.properties
----
+
[IMPORTANT]
====
the provided `application.properties` is only a template, copy it somewhere and adapt the command below
====

* create application secret
+
[source,shell]
----
kubectl create secret generic cos-fleetshard-sync-config \
    --from-file=../etc/kubernetes/sync/base/app-secret/application.properties
----
+
[IMPORTANT]
====
the provided `application.properties` is only a template, copy it somewhere and adapt the command below
====

== local profile

Start Quarkus in dev mode and read the application configuration from the current namespace.

[source,shell]
----
export KUBERNETES_NAMESPACE=$(oc project -q)

./mvnw -Plocal
----

To use a different set of configmaps/secrets:

[source,shell]
----
export KUBERNETES_NAMESPACE=$(oc project -q)

./mvnw -Plocal \
  -Dquarkus.kubernetes-config.secrets=cos-fleetshard-sync-config-1 \
  -Dquarkus.kubernetes-config.config-maps=cos-fleetshard-sync-config-1
----

By default, the application searches for:

* **Secret**: cos-fleetshard-sync-config
* **ConfigMap**: cos-fleetshard-sync-config

To change the default values, use the following system properties:
- quarkus.kubernetes-config.namespace
- quarkus.kubernetes-config.secrets
- quarkus.kubernetes-config.config-maps

== configuration options

[cols="1,1,1"]
|===
| Property | Default | Description

| cos.operators.namespace
| ${kubernetes.namespace}
| the namespace where operators are installed

| cos.resources.poll-interval
| 15s
| the interval between pool for resources

| cos.resources.resync-interval
| 60s
| the interval between full re-sync

| cos.connectors.watch
| true
| enable/disable observing resources to trigger status update

| cos.connectors.status.resync-interval
| 60s
| the interval between full connectors status re-sync

| cos.connectors.status.update-interval
| 15s
| the interval between connectors status update

| cos.cluster.status.sync-interval
| 30s
| the interval between cluster status sync

| mas-sso-base-url
|
| sso base url

| mas-sso-realm
|
| sso realm

| client-id
|
| connector cluster client id

| client-secret
|
| connector cluster client secret

| control-plane-base-url
|
| control plane base url

| cluster-id
|
| connector cluster id

|===
