---
apiVersion: "v1"
kind: "ServiceAccount"
metadata:
  labels:
    app.kubernetes.io/name: "cos-fleetshard-operator-debezium"
    app.kubernetes.io/part-of: "cos"
    app.kubernetes.io/version: "latest"
  name: "cos-fleetshard-operator-debezium"
imagePullSecrets:
- name: "addon-pullsecret"
---
apiVersion: "rbac.authorization.k8s.io/v1"
kind: "ClusterRole"
metadata:
  labels:
    app.kubernetes.io/name: "cos-fleetshard-operator-debezium"
    app.kubernetes.io/part-of: "cos"
    app.kubernetes.io/version: "latest"
  name: "cos-fleetshard-operator-debezium"
rules:
- apiGroups:
  - "cos.bf2.org"
  resources:
  - "managedconnectors"
  - "managedconnectors/status"
  - "managedconnectors/finalizers"
  - "managedconnectoroperators"
  - "managedconnectoroperators/status"
  - "managedconnectoroperators/finalizers"
  verbs:
  - "create"
  - "delete"
  - "get"
  - "list"
  - "patch"
  - "update"
  - "watch"
- apiGroups:
  - ""
  resources:
  - "secrets"
  - "configmaps"
  verbs:
  - "create"
  - "delete"
  - "get"
  - "list"
  - "patch"
  - "update"
  - "watch"
- apiGroups:
  - "kafka.strimzi.io"
  resources:
  - "kafkaconnects"
  - "kafkaconnectors"
  verbs:
  - "create"
  - "delete"
  - "get"
  - "list"
  - "patch"
  - "update"
  - "watch"
---
apiVersion: "rbac.authorization.k8s.io/v1"
kind: "ClusterRole"
metadata:
  name: "cos-fleetshard-operator-debezium-events"
rules:
- apiGroups:
  - ""
  resources:
  - "events"
  verbs:
  - "create"
  - "patch"
  - "get"
  - "list"
  - "watch"
---
apiVersion: "rbac.authorization.k8s.io/v1"
kind: "ClusterRoleBinding"
metadata:
  labels:
    app.kubernetes.io/name: "cos-fleetshard-operator-debezium"
    app.kubernetes.io/part-of: "cos"
    app.kubernetes.io/version: "latest"
  name: "cos-fleetshard-operator-debezium"
roleRef:
  apiGroup: "rbac.authorization.k8s.io"
  kind: "ClusterRole"
  name: "cos-fleetshard-operator-debezium"
subjects:
- kind: "ServiceAccount"
  name: "cos-fleetshard-operator-debezium"
  namespace: "placeholder"
---
apiVersion: "rbac.authorization.k8s.io/v1"
kind: "ClusterRoleBinding"
metadata:
  name: "cos-fleetshard-operator-debezium-events"
roleRef:
  apiGroup: "rbac.authorization.k8s.io"
  kind: "ClusterRole"
  name: "cos-fleetshard-operator-debezium-events"
subjects:
- kind: "ServiceAccount"
  name: "cos-fleetshard-operator-debezium"
  namespace: "placeholder"
---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  annotations:
    prometheus.io/path: "/q/metrics"
    prometheus.io/port: "8080"
    prometheus.io/scheme: "http"
    prometheus.io/scrape: "true"
  labels:
    app.kubernetes.io/name: "cos-fleetshard-operator-debezium"
    app.kubernetes.io/part-of: "cos"
    app.kubernetes.io/version: "latest"
  name: "cos-fleetshard-operator-debezium"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: "cos-fleetshard-operator-debezium"
      app.kubernetes.io/part-of: "cos"
      app.kubernetes.io/version: "latest"
  template:
    metadata:
      annotations:
        prometheus.io/path: "/q/metrics"
        prometheus.io/port: "8080"
        prometheus.io/scheme: "http"
        prometheus.io/scrape: "true"
      labels:
        app.kubernetes.io/name: "cos-fleetshard-operator-debezium"
        app.kubernetes.io/part-of: "cos"
        app.kubernetes.io/version: "latest"
    spec:
      containers:
      - env:
        - name: "KUBERNETES_NAMESPACE"
          valueFrom:
            fieldRef:
              fieldPath: "metadata.namespace"
        - name: "OVERRIDE_PROPERTIES_LOCATION"
          value: "/mnt/app-config/override/override.properties"
        - name: "SMALLRYE_CONFIG_LOCATIONS"
          value: "/mnt/app-config/configuration"
        image: "quay.io/rhoas/cos-fleetshard-operator-debezium:latest"
        imagePullPolicy: "Always"
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: "/q/health/live"
            port: 8080
            scheme: "HTTP"
          initialDelaySeconds: 0
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 10
        name: "cos-fleetshard-operator-debezium"
        ports:
        - containerPort: 8080
          name: "http"
          protocol: "TCP"
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: "/q/health/ready"
            port: 8080
            scheme: "HTTP"
          initialDelaySeconds: 0
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 10
        resources:
          limits:
            cpu: "1000m"
            memory: "512Mi"
          requests:
            cpu: "500m"
            memory: "512Mi"
        volumeMounts:
        - mountPath: "/mnt/app-config/configuration"
          name: "app-config"
          readOnly: false
        - mountPath: "/mnt/app-config/override"
          name: "app-config-override"
          readOnly: false
      serviceAccountName: "cos-fleetshard-operator-debezium"
      volumes:
      - configMap:
          defaultMode: 420
          name: "cos-fleetshard-operator-debezium-config"
          optional: false
        name: "app-config"
      - configMap:
          defaultMode: 420
          name: "cos-fleetshard-operator-debezium-config-override"
          optional: true
        name: "app-config-override"
---
apiVersion: "rbac.authorization.k8s.io/v1"
kind: "RoleBinding"
metadata:
  name: "cos-fleetshard-operator-debezium-view"
roleRef:
  apiGroup: "rbac.authorization.k8s.io"
  kind: "ClusterRole"
  name: "view"
subjects:
- kind: "ServiceAccount"
  name: "cos-fleetshard-operator-debezium"
---
apiVersion: "v1"
kind: "Service"
metadata:
  annotations:
    prometheus.io/path: "/q/metrics"
    prometheus.io/port: "8080"
    prometheus.io/scheme: "http"
    prometheus.io/scrape: "true"
  labels:
    app.kubernetes.io/name: "cos-fleetshard-operator-debezium"
    app.kubernetes.io/part-of: "cos"
    app.kubernetes.io/version: "latest"
  name: "cos-fleetshard-operator-debezium"
spec:
  ports:
  - name: "http"
    port: 80
    protocol: "TCP"
    targetPort: 8080
  selector:
    app.kubernetes.io/name: "cos-fleetshard-operator-debezium"
    app.kubernetes.io/part-of: "cos"
    app.kubernetes.io/version: "latest"
  type: "ClusterIP"