

generatorOptions:
  disableNameSuffixHash: true

resources:
  - ../../base/apps/cos-fleetshard-operator-camel

configMapGenerator:
  - name: cos-fleetshard-operator-camel-config
    files:
      - application.properties=app-config/application.properties

patchesJson6902:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: cos-fleetshard-operator-camel
    patch: |-
      - op: add
        path: /metadata/labels/control-plane
        value: "controller-manager"
      - op: add
        path: /spec/template/spec/containers/0/name
        value: "manager"
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: "COS_OPERATOR_ID"
          value: "cos-fleetshard-operator-camel"
