resources:
  - ../base

patchesJson6902:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: cos-fleetshard-operator-camel
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 0
      - op: replace
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: "Never"