kind: Deployment
apiVersion: apps/v1
metadata:
  name: camel-k-operator
spec:
    template:
      spec:
        containers:
        - name: camel-k-operator
          env:
          - name: WATCH_NAMESPACE            
            valueFrom:
              $patch: delete            
          #- name: KAMEL_OPERATOR_ID            
          #  value: "cos-fleetshard-operator-camel"
          - name: KAMEL_INSTALL_DEFAULT_KAMELETS
            value: "false"