kind: Deployment
apiVersion: apps/v1
metadata:
  name: camel-k-operator
spec:
    template:
      spec:
        containers:
        - name: camel-k-operator
          env:
          - name: WATCH_NAMESPACE            
            valueFrom:
              $patch: delete
          - name: KAMEL_INSTALL_DEFAULT_KAMELETS
            value: "false"
          - name: LOG_LEVEL
            valueFrom:
              configMapKeyRef:
                name: camel-k-override-config
                key: log.level
                optional: true
          - name: OPERATOR_ID
            value: "cos-fleetshard-operator-camel"
          resources:
            limits:
              cpu: "1000m"
              memory: "256Mi"
            requests:
              cpu: "100m"
              memory: "256Mi"
