resources:
  - ../base

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: cos-fleetshard-operator-camel-config
    files:
      - application.properties=app-config/application.properties

patchesJson6902:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: cos-fleetshard-operator-camel
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/name
        value: application
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: COS_OPERATOR_ID
          value: cos-fleetshard-operator-camel
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: COS_OPERATOR_VERSION
          value: "1.5.0"
      - op: replace
        path: /spec/replicas
        value: 1
      - op: replace
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: "Always"
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: "quay.io/lgarciaac/cos-fleetshard-operator-camel:latest"