package org.bf2.cos.fleetshard.operator.operand;

import org.bf2.cos.fleetshard.api.ManagedConnectorOperator;
import org.bf2.cos.fleetshard.operator.support.InstrumentedWatcherEventSource;
import org.bf2.cos.fleetshard.support.metrics.ResourceAwareMetricsRecorder;
import org.bf2.cos.fleetshard.support.resources.Resources;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import io.fabric8.kubernetes.api.model.GenericKubernetesResource;
import io.fabric8.kubernetes.api.model.OwnerReference;
import io.fabric8.kubernetes.client.KubernetesClient;
import io.fabric8.kubernetes.client.Watch;
import io.fabric8.kubernetes.client.dsl.base.ResourceDefinitionContext;
import io.javaoperatorsdk.operator.processing.event.Event;
import io.javaoperatorsdk.operator.processing.event.ResourceID;

public class OperandResourceWatcher extends InstrumentedWatcherEventSource<GenericKubernetesResource> {
    private static final Logger LOGGER = LoggerFactory.getLogger(OperandResourceWatcher.class);

    private final ManagedConnectorOperator operator;
    private final ResourceDefinitionContext context;
    private final String contextApiVersion;

    public OperandResourceWatcher(
        KubernetesClient client,
        ManagedConnectorOperator operator,
        String apiVersion,
        String kind,
        ResourceAwareMetricsRecorder recorder) {
        this(client, operator, Resources.asResourceDefinitionContext(apiVersion, kind), recorder);
    }

    public OperandResourceWatcher(
        KubernetesClient client,
        ManagedConnectorOperator operator,
        ResourceDefinitionContext context,
        ResourceAwareMetricsRecorder recorder) {

        super(client, recorder);

        this.operator = operator;
        this.context = context;
        this.contextApiVersion = context.getGroup() != null
            ? context.getGroup() + "/" + context.getVersion()
            : context.getVersion();

    }

    @Override
    protected Watch doWatch() {
        LOGGER.info("Watch resource {}:{} @ all namespaces",
            contextApiVersion,
            context.getKind());

        return getClient()
            .genericKubernetesResources(context)
            .inAnyNamespace()
            .withLabel(Resources.LABEL_OPERATOR_OWNER, operator.getMetadata().getName())
            .withLabel(Resources.LABEL_OPERATOR_TYPE, operator.getSpec().getType())
            .watch(this);
    }

    @Override
    protected void onEventReceived(Action action, GenericKubernetesResource resource) {
        if (action == Action.ADDED) {
            // skip add event as they are generated by the controller itself
            return;
        }

        if (resource.getMetadata().getOwnerReferences() == null) {
            LOGGER.debug("Ignoring action {} on resource {}:{}:{}@{} as OwnerReferences is missing",
                action,
                resource.getApiVersion(),
                resource.getKind(),
                resource.getMetadata().getName(),
                resource.getMetadata().getNamespace());

            return;
        }
        if (resource.getMetadata().getOwnerReferences().isEmpty()) {
            LOGGER.debug("Ignoring action {} on resource {}:{}:{}@{} as it does not have OwnerReferences: {}",
                action,
                resource.getApiVersion(),
                resource.getKind(),
                resource.getMetadata().getName(),
                resource.getMetadata().getNamespace(),
                resource.getMetadata().getOwnerReferences());

            return;
        }
        if (resource.getMetadata().getOwnerReferences().size() > 1) {
            LOGGER.debug("Ignoring action {} on resource {}:{}:{}@{} as it has multiple OwnerReferences: {}",
                action,
                resource.getApiVersion(),
                resource.getKind(),
                resource.getMetadata().getName(),
                resource.getMetadata().getNamespace(),
                resource.getMetadata().getOwnerReferences());

            return;
        }

        LOGGER.debug("Event {} received on resource: {}/{}/{}@{} (v{})",
            action,
            resource.getApiVersion(),
            resource.getKind(),
            resource.getMetadata().getName(),
            resource.getMetadata().getNamespace(),
            resource.getMetadata().getResourceVersion());

        //
        // Since we need to know the owner UUID of the resource to properly
        // generate the event, we can use the list of the owners
        //
        OwnerReference ownerReference = resource.getMetadata().getOwnerReferences().get(0);
        ResourceID managedConnector = new ResourceID(ownerReference.getName(), resource.getMetadata().getNamespace());
        getEventHandler().handleEvent(new Event(managedConnector));
    }
}
