name: Build Tag

on:
  push:
    tags:
      - "v*"
    paths-ignore:
      - 'LICENSE'
      - '**/.gitignore'
      - '**.md'
      - '**.adoc'
      - '*.txt'
      - 'etc/kubernetes/manifests/**'
  workflow_dispatch:

concurrency:
  group: ${{ github.ref_name}}-${{ github.workflow }}
  cancel-in-progress: true

env:
  LANG: en_US.UTF-8
  IMAGE_REPO_USERNAME: ${{secrets.IMAGE_REPO_USERNAME}}
  IMAGE_REPO_PASSWORD: ${{secrets.IMAGE_REPO_PASSWORD}}
  IMAGE_TAG: ${{ github.ref_name}}-${{ github.sha }}
  DEPLOY_TAG: ${{ github.ref_name}}-${{ github.sha }}
  OC_PROJECT: ${{ secrets.K8S_CLUSTER_DEV_NAMESPACE }}
  MAVEN_ARGS: -V -ntp -Dhttp.keepAlive=false -DskipTests=true -e

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        kubernetes:
          - 'v1.22.1'
    steps:
      - name: 'Checkout Project'
        uses: actions/checkout@v2
        with:
          ref: main
          fetch-depth: 0
      - name: 'Set up JDK 11'
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
          server-id: github
      - name: 'Login to quay.io'
        uses: docker/login-action@v1
        with:
          registry: quay.io
          username: ${{ secrets.IMAGE_REPO_USERNAME }}
          password: ${{ secrets.IMAGE_REPO_PASSWORD }}
      - name: 'Build and push container images'
        run: |          
          ./etc/scripts/build.sh
          ./etc/scripts/build_image.sh cos-fleetshard-sync
          ./etc/scripts/build_image.sh cos-fleetshard-operator-camel
          ./etc/scripts/build_image.sh cos-fleetshard-operator-debezium

  kustomize:
    needs: "build"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        overlay:
          - "staging"
    steps:
      - name: "Checkout cos-manifests project"
        uses: actions/checkout@v2
        with:
          repository: bf2fc6cc711aee1a0c2a/cos-manifests
          token: ${{ secrets.GH_TOKEN }}

      - name: "Update Kustomize overlay ${{ matrix.overlay }}"
        env:
          OVERLAY_PATH: kustomize/overlays/${{ matrix.overlay }}/data-plane
          OVERLAY_REF_REPO: ${{ github.server_url }}/${{ github.repository}}
          XDG_RUNTIME_DIR: ${{ runner.temp }}/containers
        run: |
          for APP in cos-fleetshard-sync cos-fleetshard-operator-camel cos-fleetshard-operator-debezium; do
            export REF=${OVERLAY_REF_REPO}//etc/kubernetes/manifests/overlays/staging/${APP}/?ref=${{ github.ref_name }}
            export IMAGE=quay.io/rhoas/${APP}
            export SHA256=$(skopeo inspect docker://${IMAGE}:${DEPLOY_TAG} --format "{{.Digest}}")
            
            yq -i '.resources[0] = strenv(REF)' ${OVERLAY_PATH}/${APP}/kustomization.yaml
            yq -i '.images[] |= select(.name == strenv(IMAGE)).digest = strenv(SHA256)' ${OVERLAY_PATH}/${APP}/kustomization.yaml
            yq -i 'del(.images[] | select(.name == strenv(IMAGE)).newTag)' ${OVERLAY_PATH}/${APP}/kustomization.yaml
          done

      - name: "Create PR for ${{ matrix.overlay }}"
        env:
          OVERLAY_PATH: kustomize/overlays/${{ matrix.overlay }}/data-plane
          BRANCH_NAME: "overlay.${{ matrix.overlay }}.${{ env.DEPLOY_TAG }}"
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          echo ""
          echo "tag     : $DEPLOY_TAG"
          echo "branch  : $BRANCH_NAME"
          echo ""
          cat ${OVERLAY_PATH}/kustomization.yaml
          echo ""

          git config user.email "mas-connectors@redhat.com" 
          git config user.name "mas-connectors"

          git checkout -b ${BRANCH_NAME}
          git add ${OVERLAY_PATH}
          git commit -m "Update cos-fleetshard kustomization images for overlay ${{ matrix.overlay }}" ${OVERLAY_PATH}
          git reset --hard
          git push -u origin ${BRANCH_NAME}

          # GH CLI can't find the branch on remote... needs some time :)
          sleep 15

          gh config set prompt disabled

          gh pr create \
            --fill \
            --base main \
            --title "chore(kustomize): update cos-fleetshard kustomization images overlay ${{ matrix.overlay }}" \
            --body "sha: ${{ github.sha }}, overlay: ${{ matrix.overlay }}, tag: ${DEPLOY_TAG}"