name: Integration tests

on:
  pull_request:
    types: [ opened, reopened, synchronize ]

env:
  LANG: en_US.UTF-8
  MAVEN_OPTS: -Xmx500m
  MAVEN_ARGS: -V -Dhttp.keepAlive=false -e

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Checkout Project
        uses: actions/checkout@v2

      - name: Cache m2 repo
        uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: "Integration tests"
        run: |
          mvn ${MAVEN_ARGS} clean verify

      - name: Archive results
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: artifacts
          path: systemtests/target/logs/