name: "PR"
on:
  pull_request_target:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v3
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
      - uses: shufo/auto-assign-reviewer-by-files@v1.1.3
        with:
          config: ".github/owners.yaml"
          token: ${{ secrets.GITHUB_TOKEN }}