= cos-fleetshard-operator-camel


== configuration

* create application config
+
[source,shell]
----
kubectl create configmap cos-fleetshard-operator-camel-config \
    --from-file=../etc/kubernetes/operator-camel/base/app-config/application.properties
----
+
[IMPORTANT]
====
the provided `application.properties` is only a template, copy it somewhere and adapt the command above
====

== local profile

Start Quarkus in dev mode and read the application configuration from the current namespace.

[source,shell]
----
export KUBERNETES_NAMESPACE=$(oc project -q)
export COS_OPERATOR_ID=${some_value}
export COS_OPERATOR_VERSION==${some_value}

./mvnw -Dlocal
----

By default, the application searches for:

* **ConfigMap**: cos-fleetshard-operator-camel-config

To change the default values, use the following system properties:
- quarkus.kubernetes-config.namespace
- quarkus.kubernetes-config.config-maps

== configuration options

[cols="1,1,1"]
|===
| Property | Default | Description

| cos.operator.id
|
| the id of the operator

| cos.operator.version
|
| the version of the operator

| cos.namespace
| ${kubernetes.namespace}
| the namespace where operator related resources are created
|===

== Overriding connector properties and configs

* When a camel connector is created, an empty ConfigMap is created with it.
* This ConfigMap can be used to override connector properties.
* It is created in the same namespace as the connector, with the name `mctr-<deploymentId>-configmap`.
* See `org.bf2.cos.fleetshard.support.resources.ConfigMaps.generateConnectorConfigMapId` and it's usages for more details.

One can then use that ConfigMap to override, for example, log levels for the connector, by applying the following configuration to the ConfigMap:

[source,properties]
----
quarkus.log.level=INFO
quarkus.log.min-level=ALL
quarkus.log.category."org.apache".level=ALL
quarkus.log.category."org.apache".min-level=ALL
----

Changes made to this ConfigMap triggers a redeployment of the connector with the additional supplied properties.